<?php


namespace App\Controller;


class ContentTools {
	public function __construct() {
		add_action( 'wp_ajax_tuyul_save_ideas_as_draft', [ $this, 'save_ideas_as_draft' ] );
		add_action( 'wp_ajax_tuyul_get_trend_keyword', [ $this, 'get_trend_keyword' ] );
	}

	public function save_ideas_as_draft() {
		$category = isset( $_POST['category'] ) ? (int) sanitize_text_field( $_POST['category'] ) : 1;
		$tags     = isset( $_POST['tags'] ) ? sanitize_text_field( $_POST['tags'] ) : '';
		$tags     = $tags != '' ? explode( ",", $tags ) : [];
		$ideas    = isset( $_POST['ideas'] ) ? sanitize_text_field( $_POST['ideas'] ) : [];
		$ideas    = $ideas != '' ? explode( ',', $ideas ) : [];
		if ( count( $ideas ) < 1 ) {
			echo "please select at least one idea";
			die();
		}
		foreach ( $ideas as $title ) {
			$post = array(
				'post_title'    => ucwords( $title ),
				'post_content'  => 'This post is generated by <a target="_blank" href="https://wordpress.org/plugins/tuyul-ninja/">Tuyul Ninja</a>',
				'post_status'   => 'draft',
				'post_author'   => get_current_user_id(),
				'post_category' => [ $category ],
			);
			if ( count( $tags ) > 0 ) {
				$post['tags_input'] = $tags;
			}
			wp_insert_post( $post );
		}
		wp_send_json( [
			'code'    => 200,
			'data'    => [],
			'message' => 'Ideas has been saved as post drafts'
		] );
		die();
	}

	public function get_trend_keyword() {
		$country = isset( $_POST['country'] ) ? sanitize_text_field( $_POST['country'] ) : '';
		if ( empty( $country ) ) {
			echo "Please select country";
			die();
		}
		$trends = wp_remote_request( "https://trends.google.com/trends/hottrends/atom/feed?pn=" . $country );
		$xml    = simplexml_load_string( $trends['body'] );
		$data   = [];
		foreach ( $xml->channel->item as $item ) {
			$data[] = $item->title;
		}
		wp_send_json( [
			'code'    => 200,
			'data'    => $data,
			'message' => 'Success'
		] );
		die();
	}
}